name: Pull Request Check

on: [pull_request]

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Java 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Install NDK
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.2.9519653" --sdk_root=${ANDROID_SDK_ROOT} &> /dev/null

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleRelease

      - name: Update ARM64
        uses: actions/upload-artifact@v3
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Update x86_64
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86_64-release.apk

      - name: Update ARM32
        uses: actions/upload-artifact@v3
        with:
          name: armeabi-v7a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Update x86
        uses: actions/upload-artifact@v3
        with:
          name: x86-${{ github.sha }}
          path: app/build/outputs/apk/release/app-x86-release.apk
